DATA:
  MODE: x
  DIM: 184
  CLASS_NUM: 3
  CLASS_NAMES: ['PORK', 'STUFF', 'CB']
MODEL:
  DROP: 0.
TRAIN:
  BATCH_SIZE: 128
  EPOCHS: 25
  WARMUP_EPOCHS: 0
  LR: 1e-5
  WEIGHT_DECAY: 1e-2
  LR_SCHEDULER: poly
  
